### ISSUE TITLE
Recipe conflict between Round-Robin pipe and Switchable Splitter

### ISSUE THREAD

**Issue by kraft2004** [maruohon/autoverse#3]
Hello!
I'm using the latest version of AutoVerse that is currently available in the Twitch Launcher for 1.12. However, I've encountered a problem with the recipes I mentioned. They're the same. Loaded 1.12 with only Autoverse, and I still have the problem, so, take a look at it. And also, the mod uses.. way.. too.. many.. hoppers.. Hoppers everywhere, everywhere!

**Comment by maruohon** [comment]
Oh, whoops! I'll fix that for the next version.

Yeah, so about the hoppers... they to me just indicate "a thing that moves items" in vanilla, so I often use them in recipes that somehow involve moving items. I can take a look at the recipes again. It's tricky trying to decide what is too expensive and what is too cheap, when I don't really have time to play the game normally at all, almost all of my time is spent modding.

So basically I don't have any first-hand experience trying to craft any of them in survival and seeing how much resources it will take compared to how easy or difficult getting the resources is. Plus you would then also need to consider a more vanilla-like pack without automated quarries etc. (which I feel is the type of pack Autoverse is more suited to), compared to the popular kitchen-sink packs with super fast and easy automated quarries, where people are swimming in millions of ingots of every type etc. Although then again, balancing the recipes in packs is more of a job for the pack maker, I should mostly balance against vanilla.

**Comment by kraft2004** [comment]
Thanks for fixing it!
We're in Radon, so we don't have any quarries outside Industrial Foregoing's Laser something Miner, Actually Additions Vertical Digger and the Lens of the Miner. Or Frame quarries which may be added soon, so we're not really like swimming in stuff, hehe. Thanks to your mod, tough, we can now make vanilla-like redstone plus slimeblock engines and kinda make small worm framequarries, which is cool.
Well, what you said about the hoppers makes sense. I just don't think that.. well.. so many hoppers should be used, especially for stuff such as the Buffers. Although thinking in a vanilla-minded way, where hoppers are used _**everywhere.**_, that makes sense. And, compared to TE, that is 3:6 (ingot/tubes), the pipes of Autoverse (4:4), especially Round Robins, feel like they could have their numbers pumped up a little. However, it's like you said, the pack maker is the one who decides if that's good or nah.
At the end of the day, still a good mod! :)

**Comment by maruohon** [comment]
I did end up adjusting a bunch of the recipes, generally making things a bit cheaper (like removing the hopper from a few recipes, or at least reducing the number of them, or bumping the recipe output amount etc.). I guess I might make the pipes even a bit cheaper still, if TE/TD tubes are that cheap too.

I'm currently improving some of the tooltips and documentation, and then I have a couple of bugs to fix, but I should get a new version out in a few hours I hope.

**Comment by maruohon** [comment]
This has now been fixed in version 1.0.1
