### ISSUE TITLE
Basic sequencer issue

### ISSUE THREAD

**Issue by wormzjl** [maruohon/autoverse#5]
It seems that it does not push item on redstone pulse, also I think the tooltip "Outputs one item at a time from each slot, and then advances the output slot position" should be "Outputs one item at a time from current slot, and then advances the output slot position".

**Comment by maruohon** [comment]
Huh, strange... the tooltip did indeed indicate that it was supposed to push out items on a redstone pulse, yet the TileEntity didn't have the methods at all which would schedule an update when a redstone change happens 🤔

I fixed that and also clarified the tooltip.
