### ISSUE TITLE
Block detector not working as intended

### ISSUE THREAD

**Issue by wormzjl** [maruohon/autoverse#9]
If it detects the correct item but the detection items buffer is empty, item in the others buffer will be sent out instead.
I think in such cases it should not send out items to prevent issues?

**Comment by wormzjl** [comment]
That depends also on the application...What was the designed purpose anyway?

**Comment by wormzjl** [comment]
Oh I see, I was thinking about that the resources are underground like vanilla :P

**Comment by maruohon** [comment]
Yeah for that it would need to be a cheaty x-ray sniffer :p

But I would imagine in an underground use case the whole thing is usually a frame quarry, so you basically just drive it through the terrain in straight lines and gather whatever is there.

**Comment by wormzjl** [comment]
Omnidirectional ore-eater worm yeah, but still one can tweak the ore gen to
make it looks like a cloud or something.

Matti Ruohonen <notifications@github.com> 于 2018年9月20日周四 01:11写道：
